LoadApi first commit
liveasy97/loadsApi pull request #8
Opened 2021-05-02 11:21 UTC by vivekbhosale

Made some changes. Check it and let me know if any changes required.

2021-05-09 11:08 UTC, jsrub requested changes

2021-05-13 07:56 UTC, vivekbhosale commented on TruckBooking/src/main/java/com/TruckBooking/TruckBooking/Service/LoadServiceImpl.java
> +			return list;
Done

2021-05-13 08:33 UTC, vivekbhosale commented on TruckBooking/src/main/java/com/TruckBooking/TruckBooking/Service/LoadServiceImpl.java
> +	public LoadResponse updatePostAload(String loadId, LoadRequest loadRequest) {
Done

2021-05-13 08:35 UTC, vivekbhosale commented on TruckBooking/src/main/java/com/TruckBooking/TruckBooking/Service/LoadServiceImpl.java
> +	public LoadResponse updatePostAload(String loadId, LoadRequest loadRequest) {
Done

2021-05-13 11:30 UTC, closed without merging